#!/usr/bin/env ruby

require 'yaml'

project_name = ARGV[0]
path = File.expand_path("~/Projects/launchers/#{project_name}.yml")

if not File.exists?(path)
  puts "Project #{project_name} not found."
  abort
end

begin
    project_yaml = YAML.load_file(path)
rescue Exception
  puts "Cannot read YAML file."
end

puts project_yaml['name']
puts " "
key = ARGV[1]

if not key
  project_yaml.keys.each_with_index do |x, i|
    puts "#{i}: #{x}"
  end

  puts "Please make a selection:"
  selection = STDIN.gets
  key = project_yaml.keys[selection.to_i]
end

puts "Executing #{key}"

if not project_yaml[key]
  puts "Command with key #{key} not found."
  abort
end

if project_yaml['project_path']
  Dir.chdir(project_yaml['project_path'])
end

command = project_yaml[key].join("; ")
if ARGV.length() > 2
  command = command.sub("###args###", ARGV[2..-1].join(" "))
end

puts command
exec(command)
